name: fixsidang
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  alarm: ^3.0.5
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.3
  connectivity_plus: ^5.0.2
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  firebase_auth: 4.15.0
  firebase_core: 2.24.2
  firebase_database: ^10.4.0
  flutter_background_service: ^3.0.1
  flutter_local_notifications: ^16.3.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: 4.6.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  permission_handler: ^9.0.2
  random_avatar: ^0.0.8
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/lotties/
  uses-material-design: true
