// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwgv_XFk7Fzl9LX37pWYBoJUCf_WHr6Rc',
    appId: '1:289928100421:web:a94b577a64108b429b012c',
    messagingSenderId: '289928100421',
    projectId: 'slbncicendonew',
    authDomain: 'slbncicendonew.firebaseapp.com',
    databaseURL: 'https://slbncicendonew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slbncicendonew.appspot.com',
    measurementId: 'G-953B0TGMK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNeLDcy24Uki0aR_xyD8YuqgO5xGeCIY',
    appId: '1:289928100421:android:8867af948bbe4cdd9b012c',
    messagingSenderId: '289928100421',
    projectId: 'slbncicendonew',
    databaseURL: 'https://slbncicendonew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slbncicendonew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhYeRQzhWCLvO8FwgRo2YXWINHk51o98',
    appId: '1:289928100421:ios:a0b26eff373dea249b012c',
    messagingSenderId: '289928100421',
    projectId: 'slbncicendonew',
    databaseURL: 'https://slbncicendonew-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slbncicendonew.appspot.com',
    iosBundleId: 'com.fixsidang.fixsidang',
  );
}
